Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,17 +17,11 @@ services:
       - 'c *:* rwm'
     network_mode: "bridge"
     restart: unless-stopped
-    stdin_open: true   # Keeps STDIN open even if not attached
-    tty: true          # Allocates a pseudo-TTY
+    stdin_open: true  
+    tty: true         
     healthcheck:
-      test: >
-        bash -c '
-        OUTPUT=$(nrsc5 99.9 0 -o 1.wav 2>&1 || true);
-        if echo "$OUTPUT" | grep -q "usb_open error -4"; then
-        kill -s SIGTERM 1;
-        exit 1;
-        fi
-        '
+      test: ["CMD-SHELL", "bash -c 'OUTPUT=$(nrsc5 99.9 0 -o /dev/null 2>&1 || true); if echo \"$OUTPUT\" | grep -q \"usb_open error\"; then exit 1; fi; exit 0'"]
       interval: 30s
       timeout: 5s
-      retries: 1
+      retries: 2
+      start_period: 10s   
